config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?
  devise_for :users # ユーザーのログイン・登録などに必要なルート
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "home#index"

  resource :profile, only: [ :edit, :update ]

  # 診察記録と紐づく予定
  resources :visits, except: [ :show ] do
    collection do
      get :by_date # 現在使用中
    end

    # 診察記録に紐づく質問選択・編集
    resources :question_selections, only: [ :index, :create, :update, :destroy ]

    # 診療記録に紐ついている録音 Visit に対して録音は1件しか紐づかない想定なので、ルートは単数
    # 医療業界では録音に厳しい状況もあるため、更新はなしとする。
    resource :recording, only: [ :new, :create, :show, :destroy ]

    # 画像アップロード
    resources :documents, only: [ :index, :new, :create, :edit, :update, :destroy ]
  end

  # 質問テンプレを選択、検索
  resources :questions do
    collection do
      get :select
      get :search
    end
  end

  # Chrome DevToolsが勝手に叩く .well-knownのリクエストを表示させないようにしたい
  match "/.well-known/*path", to: ->(env) { [ 204, { "Content-Type" => "text/plain" }, [ "" ] ] }, via: :all
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :birthday, presence: true
  validates :gender, presence: true
  validates :height, :weight, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true

  enum :gender, { male: 0, female: 1 }
  BLOOD_TYPES = [ "A型", "B型", "O型", "AB型", "不明" ].freeze
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile

  def edit
    @profile = current_user.profile || current_user.build_profile
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path, notice: "プロフィールを更新しました。"
    else
      flash.now[:error] = "更新できませんでした。"
      render :edit, status: :unprocessable_entity
    end
  end


  private

  def set_profile
    @profile = current_user.profile || current_user.build_profile
  end

  def profile_params
    # expectではテストでエラーが出るため
    params.require(:profile).permit(
      :birthday,
      :gender,
      :height,
      :weight,
      :blood_type,
      :allergy_details,
      :medical_history,
      :current_medication
    )
  end
end

app/views/profiles/edit.html.erb
<div class="d-flex justify-content-start">
  <%= link_to visits_path, class: "btn btn-outline-secondary d-flex align-items-center back-button" do %>
    <i class="bi bi-arrow-left-circle-fill me-2"></i>
    戻る
  <% end %>
</div>

<div class="container">
  <div class="form-container">
    <h2 class="form-title text-center text-pink">プロフィール</h2>
       <p class="text-center">登録内容を変更できます</p>

    <% if @profile.errors.any? %>
      <div class="error-messages">
        <ul>
          <% @profile.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: @profile, url: profile_path, method: :patch, local: true) do |f| %>
      <div class="mb-3">
        <label class="form_label">名前</label>
        <p class="form-control-plaintext"><%= current_user.name %></p>
      </div>

      <div>
        <%= f.label :birthday, "生年月日" %>
        <%= f.date_field :birthday, class: 'form-control' %>
      </div>

      <div>
        <%= f.label :gender, "性別" %>
        <%= f.select :gender, Profile.genders.keys.map { |k, v| [ I18n.t("enums.profile.gender.#{k}"), k ] }, {}, { class: 'form-select' } %>
      </div>

      <div>
        <%= f.label :height, "身長(cm)" %>
        <%= f.number_field :height, class: 'form-control' %>
      </div>

      <div>
        <%= f.label :weight, "体重(kg)" %>
        <%= f.number_field :weight, class: 'form-control' %>
      </div>

      <div>
        <%= f.label :blood_type, "血液型" %>
        <%= f.select :blood_type, Profile::BLOOD_TYPES, {}, { class: 'form-select' } %>
      </div>

      <div>
        <%= f.label :allergy_details, "アレルギー歴" %>
        <%= f.text_area :allergy_details, class: "form-control" %>
      </div>

      <div>
        <%= f.label :medical_history, "既往歴" %>
        <%= f.text_area :medical_history, class: "form-control" %>
      </div>

      <div>
        <%= f.label :current_medication, "内服薬" %>
        <%= f.text_area :current_medication, class: "form-control" %>
      </div>

      <div class="text-center mt-4">
        <%= f.submit "保存", class: "btn btn-outline-pink btn-lg px-5 py-3" %>
      </div>
    <% end %>
  </div>
</div>