config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?
  devise_for :users # ユーザーのログイン・登録などに必要なルート
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "home#index"

  resource :profile, only: [ :edit, :update ]

  # 診察記録と紐づく予定
  resources :visits, except: [ :show ] do
    collection do
      get :by_date # 現在使用中
    end

    # 診察記録に紐づく質問選択・編集
    resources :question_selections, only: [ :index, :create, :update, :destroy ]

    # 診療記録に紐ついている録音 Visit に対して録音は1件しか紐づかない想定なので、ルートは単数
    # 医療業界では録音に厳しい状況もあるため、更新はなしとする。
    resource :recording, only: [ :new, :create, :show, :destroy ]

    # 画像アップロード
    resources :documents, only: [ :index, :new, :create, :edit, :update, :destroy ]
  end

  # 質問テンプレを選択、検索
  resources :questions do
    collection do
      get :select
      get :search
    end
  end

  # Chrome DevToolsが勝手に叩く .well-knownのリクエストを表示させないようにしたい
  match "/.well-known/*path", to: ->(env) { [ 204, { "Content-Type" => "text/plain" }, [ "" ] ] }, via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Yorisoi Note2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-FE0A..." crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <%# cdnからでないと、カレンダーが正常に読み込まれない %>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "/js/calendar.js" %>
    <%= javascript_include_tag "/js/locales-all.global.js" %>
  </head>

  <body>
    <%# 「ログインしている場合」かつ「questions#selectまたはquestions#searchアクションではない場合」だけ処理を実行したい %>
  <% if user_signed_in? && controller_name == 'visits' && action_name == 'index' %>
    <%# トグルボタン %>
    <div class="login-user-banner d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center">
        <button id="menuToggle" class="hamburger-btn me-3" aria-label="メニューを開く">
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
        </button>
        <p class="mb-0">ようこそ、<strong><%= current_user.name %></strong>さん</p>
      </div>
      <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-pink-override btn-logout' %>
    </div>

    <nav id="sidebarMenu" class="sidebar">
      <div class="inner">
        <ul class="sidebar-nav">
          <li><%= link_to "スケジュールを確認する", visits_path %></li>
          <li><%= link_to "受診に関する画像を確認する", visit_documents_path(current_user.visits.last) if current_user.visits.any? %></li>
          <li><%= link_to "プロフィールを見る", edit_profile_path %></li>
          <li><%= link_to "パスワードを変更する", edit_user_registration_path %></li>
        </ul>
      </div>
    </nav>
  <% end %>

  <% flash.each do |key, message| %>
    <div class="flash-message flash-<%= key %>">
      <%= message %>
    </div>
  <% end %>

  <%= yield %>
  <%= yield :javascript %>
</body>
</html>